var defaultWidgetModel = [
    '{"selectedDataKey":"Shopper Stop","segmentModel":{"chartType":"line","selection":{"complexGroups":[],"props":[{"prop":"price","groupBy":"sum"}]},"dataGroup":{"xAxisProp":"timestamp","groupByProp":"sex","timeseries":true,"interval":"4000000","hasGrouping":true,"hasDivideBy":false,"xAxisType":"time"},"group":{"groupType":"conditions","groups":[],"renderType":"group"},"properties":["price","geography","timestamp","sex","color","tax","shippingPrice"]},"sizex":"1"}',
    '{"selectedDataKey":"Shopper Stop","segmentModel":{"chartType":"bar","selection":{"complexGroups":[],"props":[{"prop":"price","groupBy":"sum"},{"prop":"color","groupBy":"count"}]},"dataGroup":{"template":"datagroup-template","groupByProp":"geography","hasGrouping":true,"divideByProp":"color","hasDivideBy": true},"group":{"groupType":"conditions","groups":[],"renderType":"group"},"properties":["price","geography","timestamp","sex","color","tax","shippingPrice"]},"sizex":"2"}',
    '{"selectedDataKey":"Shopper Stop","segmentModel":{"chartType":"pie","selection":{"complexGroups":[],"props":[{"prop":"geography","groupBy":"count"}]},"dataGroup":{"template":"datagroup-template","groupByProp":"geography","hasGrouping":true,"divideByProp":"color","hasDivideBy": true},"group":{"groupType":"conditions","groups":[],"renderType":"group"},"properties":["price","geography","timestamp","sex","color","tax","shippingPrice"]},"sizex":"1"}',
    '{"selectedDataKey":"Shopper Stop","segmentModel":{"chartType":"area","selection":{"complexGroups":[{"groupType":"selections", "groupBy" : "sum", "groups":[{"prop":"price","logic":"-","conditionType":"selections","renderType":"condition"},{"prop":"shippingPrice","logic":"-","conditionType":"selections","renderType":"condition"},{"prop":"tax","logic":"-","conditionType":"selections","renderType":"condition"}],"logic":"+","renderType":"group","selectionName":"Price-Tax-Shipping"}],"props":[{"prop":"price","groupBy":"sum"}]},"dataGroup":{"template":"datagroup-template","xAxisProp":"timestamp","xAxisType": "linear","groupByProp":"geography","timeseries":true,"hasGrouping":true,"interval":"400"},"group":{"groupType":"conditions","groups":[],"renderType":"group"},"properties":["price","geography","timestamp","sex","color","tax","shippingPrice"]},"sizex":"2"}',
    '{"selectedDataKey":"Shopper Stop","segmentModel":{"chartType":"scatter","selection":{"complexGroups":[],"props":[{"prop":"price","groupBy":"sum"},{"prop":"tax","groupBy":"sum"},{"prop":"color","groupBy":"count"}]},"dataGroup":{"template":"datagroup-template","xAxisProp":"timestamp","xAxisType": "linear", "groupByProp":"geography","timeseries":true,"hasGrouping":true,"interval":"200"},"group":{"groupType":"conditions","groups":[],"renderType":"group"},"properties":["price","geography","timestamp","sex","color","tax","shippingPrice"]},"sizex":"2"}'
    ];

    var widgets = defaultWidgetModel.map(function(item){
        return JSON.parse(item);
    })
    window.dashboardModel = {
        name: 'maneesh',
        widgets: widgets
    };